from src.problem_domain.base_problem import BaseProblem
from src.problem_domain.com_influence_max_problem import ComInfluenceMaxProblem
from src.problem_domain.compiler_args_selection_problem import CompilerArgsSelectionProblem
from src.problem_domain.contamination_problem import ContaminationProblem
from src.problem_domain.surrogate_problem import SurrogateProblem
from src.problem_domain.match_max_problem import MatchMaxProblem
from src.problem_domain.zero_one_knapsack_problem import ZeroOneKnapsackProblem
from src.problem_domain.max_cut_problem import MaxCutProblem
