model_params:
  name: 'SurrogateVAE'
  in_dim: 10
  latent_dim_coefficient: 1
  latent_dim: 128
  hidden_dims: [ 128, 128 ]
  mlp_dims: [ 256, 512, 256 ]
  lamBDa: 1
  gamma: 0.0025
  margin: 4

data_params:
  data_path: "data/"
  train_batch_size: 8192
  val_batch_size: 8192
  num_workers: 0

exp_params:
  LR: 0.0005
  weight_decay: 0.00001
  manual_seed: 1088

trainer_params:
  gpus: [ 1 ]
  max_epochs: 50000

logging_params:
  save_dir: "/home/metaron/EMPI_exp/logs/surrogate_train_logs"
  manual_seed: 1088
  name: 'SurrogateVAE'
